# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665fd2563b36c4973ca1856edcb60621da0014b8ca744eed0ba2e54e537aa04d6074dd90958d663f5eb1bc0580fd5db76da422291ce5340c81462913d4fa27e1

test:
  secret_key_base: 78db4d1b071c579719f679092ed742dd2a8824d5b2eb08c10b434c3326196d10324683453bb4727bcc593b975f62e17ded9b37de4c5d8ea08f5688b8e1f7cbfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
